version: "3.9"

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ../../src/api-gateway
      dockerfile: ../../src/api-gateway/Dockerfile
    ports:
      - "80:80"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3000
      - ML_SERVICE_URL=http://ml-service:3001
      - APP_SERVICE_URL=http://app-service:3002
    env_file:
      - "../../src/api-gateway/.env"
    networks:
      - auth-network
